version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
    ignore:
      - dependency-name: "@babel/core"
        versions: [">=8"]
    groups:
      babel:
        patterns:
          - "@babel/*"
      fumadocs:
        patterns:
          - "fumadocs-*"
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
          - "typescript-eslint"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
